name: Latex Builder

on: [push]

jobs:
  make-it:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install LaTex utilities
        run:  sudo apt update && sudo apt-get install -y texlive-full
      - name: Get version from file
        id: get_version
        run: echo "VERSION=version/$(cat version)" >> $GITHUB_ENV
      - name: Name release from version
        id: get_release
        run: echo "RELEASE=release_$(cat version)" >> $GITHUB_ENV
      - name: Build PDFs
        run: make
      - name: Upload PDFs archives
        uses: actions/upload-artifact@v4
        with:
          name: modules.pdf
          path: |
            build/module00.pdf
            build/module01.pdf
            build/module02.pdf
            build/module03.pdf
            build/module04.pdf